name: cppcheck_lab6

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt install cppcheck
      # ------------- Tests ----------------
      - name: test_lab6_part1
        run: |
          cppcheck Lab6-PIO-IRQ-RTOS\PIO-IRQ-RTOS/src -iLab6-PIO-IRQ-RTOS\PIO-IRQ-RTOS/src/ASF --enable=style,warning,performance > lab6_1.txt
      # ------------- Tests ----------------
      - name: test_lab6_part2
        run: |
          cppcheck Lab6-ADC-IRQ-RTOS/src -iLab6-ADC-IRQ-RTOS/src/ASF --enable=style,warning,performance > lab6_2.txt
      # ------------- report ----------------
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' # your branch name goes here