name: cppcheck_lab9

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt install cppcheck
      # ------------- Tests ----------------
      - name: test_lab9
        id: lab9
        run: |
          cppcheck Lab9-RTOS-WIFI/RTOS-WIFI-WINC1500-get-EXT1/src -iLab9-RTOS-WIFI/RTOS-WIFI-WINC1500-get-EXT1/src/ASF --enable=style,warning,performance 2> lab9.txt
          echo "log=$lab9.txt" >>$GITHUB_OUTPUT
      # ------------- issues ----------------
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        if: ${{ steps.test.log }}
        with:
          title: Issues Lab 9
          content-filepath: lab9.txt
          labels: |
            report
            automated issue
      # ------------- Fail ----------------
      - name: Error
        if: ${{ steps.test.log }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Erro no Lab 9')