name: cppcheck_lab4

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt install cppcheck
      # ------------- Tests ----------------
      - name: test_lab4
        run: |
          cppcheck Lab4-TC-RTC-RTT/src -iLab4-TC-RTC-RTT/src/ASF --enable=style,warning,performance 2> lab4.txt
          echo ::set-output name=log::lab4.txt
      # ------------- issues ----------------
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        if: steps.id.outputs.log != ' '
        with:
          title: Issues Lab 4
          content-filepath: lab4.txt
          labels: |
            report
            automated issue
      # ------------- Fail ----------------
      - name: Error
        if: steps.id.outputs.log != ' '
        run:
          echo "Erro no Lab 4"
          exit 1