name: cppcheck_lab9

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt install cppcheck
      # ------------- Tests ----------------
      - name: test_lab9
        run: |
          cppcheck Lab9-RTOS-WIFI/RTOS-WIFI-WINC1500-get-EXT1/src -iLab9-RTOS-WIFI/RTOS-WIFI-WINC1500-get-EXT1/src/ASF --enable=style,warning,performance > lab9.txt
      # ------------- report ----------------
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' # your branch name goes here