name: cppcheck_lab5

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt install cppcheck
      # ------------- Tests ----------------
      - name: test_lab5
        id: lab5
        run: |
          cppcheck Lab5-HC-SR04/OLED-Xplained-Pro-SPI/src -iLab5-HC-SR04/OLED-Xplained-Pro-SPI/src/ASF --enable=style,warning,performance 2> lab5.txt
          cat lab5.txt
      # ------------- issues ----------------
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Report Lab 5
          content-filepath: lab5.txt
          labels: |
            report
            automated issue
      # ------------- Fail ----------------
      - name: Error
        run: |
          python3 .github/parser.py lab5.txt
