name: cppcheck_lab3

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt install cppcheck

      # ------------- Tests ----------------
      - name: test_lab3_part1
        id: lab3_1
        run: |
          cppcheck Lab3-PIO-IRQ/PIO/src -iLab3-PIO-IRQ/PIO/src/ASF --enable=style,warning,performance 2> lab3_1.txt
          echo echo "log=$lab3_1.txt" >>$GITHUB_OUTPUT
      # ------------- issues ----------------
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        if: ${{ steps.test.log }}
        with:
          title: Issues Lab 3_1
          content-filepath: lab3_1.txt
          labels: |
            report
            automated issue
      # ------------- Tests ----------------
      - name: test_lab3_part2
        id: lab3_2
        run: |
          cppcheck Lab3-OLED-PIO-IRQ/src -iLab3-OLED-PIO-IRQ/src/ASF --enable=style,warning,performance 2> lab3_2.txt
          echo "log=$lab3_2.txt" >>$GITHUB_OUTPUT
      # ------------- issues ----------------
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        if: ${{ steps.test.log }}
        with:
          title: Issues Lab 3_2
          content-filepath: lab3_2.txt
          labels: |
            report
            automated issue
      # ------------- Fail ----------------
      - name: Error
        if: ${{ steps.test.log }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Erro no Lab 3.1')
      # ------------- Fail ----------------
      - name: Error
        if: ${{ steps.test.log }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Erro no Lab 3.2')